services:
  mysql-service:
    container_name: mysql-service
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_connect_db
    networks:
      - job_connect_network
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-service", '-uroot', '-proot' ]
      timeout: 20s
      interval: 5s
      retries: 5
      start_period: 60s

  job-connect-backend:
    container_name: job-connect-backend
    image: ${{ secrets.DOCKER_USERNAME }}/job-connect-backend:latest
    ports:
      - "8181:8181"
    networks:
      - job_connect_network
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8181/api/v1.0.0/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s

  job-connect-frontend:
    container_name: job-connect-frontend
    image: ${{ secrets.DOCKER_USERNAME }}/job-connect-frontend:latest
    ports:
      - "8080:80"
    networks:
      - job_connect_network
    depends_on:
      job-connect-backend:
        condition: service_healthy
    restart: always

networks:
  job_connect_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local