version: '3.8'

services:
  mysql-service:
    container_name: mysql-service
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_connect_db
    networks:
      - job_connect_network
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", '-uroot', '-proot']
      timeout: 20s
      interval: 5s
      retries: 5
      start_period: 60s

networks:
  job_connect_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
