apiVersion: v1
kind: Service
metadata:
  name: job-connect-backend
  namespace: devops
spec:
  ports:
    - port: 8181
      targetPort: 8181
  selector:
    app: job-connect-backend
  type: LoadBalancer