apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-connect-backend
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-connect-backend
  template:
    metadata:
      labels:
        app: job-connect-backend
    spec:
      containers:
        - name: springboot-app
          image: rupesh1997/job-connect-backend:1.0.0
          ports:
            - containerPort: 9191
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MYSQL_ROOT_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"