apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # ✅ Updated from "local-storage" to "standard"
  resources:
    requests:
      storage: 1Gi
