spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/job_connect_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
  cache:
    disabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

application:
  cors:
    origins: http://localhost:4200,http://localhost:8080,http://20.55.25.220:8080,http://20.55.25.220:8181
  security:
    token:
      secret_key: 6WAG0O1I5ACSQ1ZMO6ZSEDCJ3RFOMC1Q1BC4MLWEBYBL3UAH91B6NWLXNH4NGN8URT2AEEMTHXHNB2FMRFVJY4JKL88LYHMPYTZCA3GNEVM4N9Q37ZSF4DEUVLDLP
      expiration: 3600000